# required input files
#   [refcartfl] - reference Cartesian geometry, COLUMBUS format
#   gf.x, which itself requires:
#     fit.in
#     refgeom
#     intcfl
#     basis.in
#     Hd.CheckPoint
#     automatically generated by this program:
#       geom.all
#       energy.all
# generated output files
#   gf.x generates:
#     hess
#     molden.freq
#     gf.log

# parameters
#refcartfl = "ORIGIN/geom" # Path of initial Cartesian geometry file
state = 1
ncoord = 6 # Number of internal coordinates

# module import
import numpy as np
import os
import subprocess
print("Modules imported")

# create geometry file
#os.system("cp " + refcartfl + " ./geom.all")

def getlatestSLURM(directory: str) -> str:
    '''retrieve path of latest-generated SLURM output file
    directory: path to directory containing SLURM files'''
    directory += '/24'
    SLURM_files = [ f.name for f in os.scandir(directory) if (f.is_file() and ("slurm-" in f.name)) ]
    SLURM_nums = [ int(filename[6:-4]) for filename in SLURM_files ]
    SLURM_nums.sort(reverse = True)
    print(SLURM_nums)
    print(SLURM_nums[0])
    last_SLURM = "slurm-" + str(SLURM_nums[0]) + ".out"
    return directory + "/" + last_SLURM

def getener(directory: str) -> list:
    '''retrieves energies from a completed CFOUR calculation
    directory: path to directory containing CFOUR calculation
    returns energies as strings in a list'''
    f = open(getlatestSLURM(directory), "r")
    lines = f.readlines()
    f.close()
    # maybe insert a check here that the calculation converged
    eners = []
    for line in lines:
        if "Total EOMEA-CCSD electronic energy" in line:
            eners.append(line.split()[-2])
    return eners

# energy extraction function
def displace(target, ref = False):
    energy = getener(target)[0]
    if ref:
        filecmd = "w"
    else:
        filecmd = "a"
    f = open("energy.all", filecmd)
    f.write(energy + "\n")
    f.close()

# reference geometry
displace("E0",  True)
# single coordinate displacement
for i in range(ncoord):
    print("\ni = " + str(i + 1))
    target = "i" + str(i + 1)
    displace(target)
# pairwise coordinate displacements
for i in range(ncoord):
    for j in range(i, ncoord):
        print("\ni = " + str(i + 1) + "    j = " + str(j + 1))
        target = "i" + str(i + 1) + "j" + str(j + 1)
        displace(target)
"""
# run gf.x
rv = subprocess.run(["./gf.x"],cwd="./",capture_output=True)
f = open("./gf.log", "w")
f.write(rv.stdout.decode('utf8'))
f.close()
print("gf.x completed")
print(rv.stdout.decode('utf8'))
"""

